from ...protocol import *
import sublime
from _typeshed import Incomplete
from typing import Any, Generic, Iterable, Mapping, TypeVar, TypedDict
from typing_extensions import NotRequired

INT_MAX: Incomplete
UINT_MAX = INT_MAX
R = TypeVar('R')

class Request(Generic[R]):
    __slots__: Incomplete
    method: Incomplete
    params: Incomplete
    view: Incomplete
    progress: bool | str
    partial_results: Incomplete
    def __init__(self, method: str, params: Any = None, view: sublime.View | None = None, progress: bool = False, partial_results: bool = False) -> None: ...
    @classmethod
    def initialize(cls, params: InitializeParams) -> Request: ...
    @classmethod
    def complete(cls, params: CompletionParams, view: sublime.View) -> Request: ...
    @classmethod
    def signatureHelp(cls, params: SignatureHelpParams, view: sublime.View) -> Request: ...
    @classmethod
    def codeAction(cls, params: CodeActionParams, view: sublime.View) -> Request: ...
    @classmethod
    def documentColor(cls, params: DocumentColorParams, view: sublime.View) -> Request: ...
    @classmethod
    def colorPresentation(cls, params: ColorPresentationParams, view: sublime.View) -> Request: ...
    @classmethod
    def willSaveWaitUntil(cls, params: WillSaveTextDocumentParams, view: sublime.View) -> Request: ...
    @classmethod
    def documentSymbols(cls, params: DocumentSymbolParams, view: sublime.View) -> Request: ...
    @classmethod
    def documentHighlight(cls, params: DocumentHighlightParams, view: sublime.View) -> Request: ...
    @classmethod
    def documentLink(cls, params: DocumentLinkParams, view: sublime.View) -> Request: ...
    @classmethod
    def semanticTokensFull(cls, params: SemanticTokensParams, view: sublime.View) -> Request: ...
    @classmethod
    def semanticTokensFullDelta(cls, params: SemanticTokensDeltaParams, view: sublime.View) -> Request: ...
    @classmethod
    def semanticTokensRange(cls, params: SemanticTokensRangeParams, view: sublime.View) -> Request: ...
    @classmethod
    def prepareCallHierarchy(cls, params: CallHierarchyPrepareParams, view: sublime.View) -> Request[list[CallHierarchyItem] | Error | None]: ...
    @classmethod
    def incomingCalls(cls, params: CallHierarchyIncomingCallsParams) -> Request: ...
    @classmethod
    def outgoingCalls(cls, params: CallHierarchyOutgoingCallsParams) -> Request: ...
    @classmethod
    def prepareTypeHierarchy(cls, params: TypeHierarchyPrepareParams, view: sublime.View) -> Request: ...
    @classmethod
    def supertypes(cls, params: TypeHierarchySupertypesParams) -> Request: ...
    @classmethod
    def subtypes(cls, params: TypeHierarchySubtypesParams) -> Request: ...
    @classmethod
    def resolveCompletionItem(cls, params: CompletionItem, view: sublime.View) -> Request: ...
    @classmethod
    def resolveDocumentLink(cls, params: DocumentLink, view: sublime.View) -> Request: ...
    @classmethod
    def inlayHint(cls, params: InlayHintParams, view: sublime.View) -> Request: ...
    @classmethod
    def resolveInlayHint(cls, params: InlayHint, view: sublime.View) -> Request: ...
    @classmethod
    def rename(cls, params: RenameParams, view: sublime.View, progress: bool = False) -> Request: ...
    @classmethod
    def prepareRename(cls, params: PrepareRenameParams, view: sublime.View, progress: bool = False) -> Request: ...
    @classmethod
    def selectionRange(cls, params: SelectionRangeParams) -> Request: ...
    @classmethod
    def foldingRange(cls, params: FoldingRangeParams, view: sublime.View) -> Request: ...
    @classmethod
    def workspaceSymbol(cls, params: WorkspaceSymbolParams) -> Request: ...
    @classmethod
    def resolveWorkspaceSymbol(cls, params: WorkspaceSymbol) -> Request: ...
    @classmethod
    def documentDiagnostic(cls, params: DocumentDiagnosticParams, view: sublime.View) -> Request: ...
    @classmethod
    def workspaceDiagnostic(cls, params: WorkspaceDiagnosticParams) -> Request: ...
    @classmethod
    def shutdown(cls) -> Request: ...
    def __repr__(self) -> str: ...
    def to_payload(self, id: int) -> dict[str, Any]: ...

class Error(Exception):
    code: Incomplete
    data: Incomplete
    def __init__(self, code: int, message: str, data: Any = None) -> None: ...
    @classmethod
    def from_lsp(cls, params: ResponseError) -> Error: ...
    def to_lsp(self) -> dict[str, Any]: ...
    def __str__(self) -> str: ...
    @classmethod
    def from_exception(cls, ex: Exception) -> Error: ...
T = TypeVar('T', bound=None | bool | int | Uint | float | str | Mapping[str, Any] | Iterable[Any])

class Response(Generic[T]):
    __slots__: Incomplete
    request_id: Incomplete
    result: Incomplete
    def __init__(self, request_id: Any, result: T) -> None: ...
    def to_payload(self) -> dict[str, Any]: ...

class Notification:
    __slots__: Incomplete
    method: Incomplete
    params: Incomplete
    def __init__(self, method: str, params: Any = None) -> None: ...
    @classmethod
    def initialized(cls) -> Notification: ...
    @classmethod
    def didOpen(cls, params: DidOpenTextDocumentParams) -> Notification: ...
    @classmethod
    def didChange(cls, params: DidChangeTextDocumentParams) -> Notification: ...
    @classmethod
    def willSave(cls, params: WillSaveTextDocumentParams) -> Notification: ...
    @classmethod
    def didSave(cls, params: DidSaveTextDocumentParams) -> Notification: ...
    @classmethod
    def didClose(cls, params: DidCloseTextDocumentParams) -> Notification: ...
    @classmethod
    def didChangeConfiguration(cls, params: DidChangeConfigurationParams) -> Notification: ...
    @classmethod
    def didChangeWatchedFiles(cls, params: DidChangeWatchedFilesParams) -> Notification: ...
    @classmethod
    def didChangeWorkspaceFolders(cls, params: DidChangeWorkspaceFoldersParams) -> Notification: ...
    @classmethod
    def exit(cls) -> Notification: ...
    def __repr__(self) -> str: ...
    def to_payload(self) -> dict[str, Any]: ...

class Point:
    row: Incomplete
    col: Incomplete
    def __init__(self, row: int, col: int) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: object) -> bool: ...
    @classmethod
    def from_lsp(cls, point: Position) -> Point: ...
    def to_lsp(self) -> Position: ...
    def __gt__(self, other): ...
    def __le__(self, other): ...
    def __ge__(self, other): ...

class ResponseError(TypedDict):
    code: int
    message: str
    data: NotRequired['LSPAny']

class ResolvedCodeLens(TypedDict):
    range: Range
    command: Command
    uses_cached_command: NotRequired[bool]
RangeLsp = Range
